// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : CrossValidation::BDTG
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/06       [399366]
Creator        : fsimone
Date           : Mon Mar  7 10:37:11 2022
Host           : Linux 88470cd8874b 5.8.0-1040-azure #43~20.04.1-Ubuntu SMP Mon Aug 2 22:06:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /lustrehome/fsimone/MVA_CrossValidation_Run2
Training events: 175541
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
EncapsulatedMethodName: "BDTG" []
EncapsulatedMethodTypeName: "BDT" []
NumFolds: "5" [Number of folds to generate]
OutputEnsembling: "None" [Combines output from contained methods. If None, no combination is performed. (default None)]
SplitExpr: "int(fabs([evt]))%int([NumFolds])" [The expression used to assign events to folds]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
Pt_tripl                      Pt_tripl                      Pt_tripl                      Pt_tripl                                                        'D'    [10.1220970154,159.431533813]
cLP>30?30:cLP                 cLP_30_30:cLP                 cLP>30?30:cLP                 cLP                                                             'D'    [0.046971462667,30]
tKink>80?80:tKink             tKink_80_80:tKink             tKink>80?80:tKink             tKink                                                           'D'    [1.63035964966,80]
segmComp<0.2?0.2:segmComp     segmComp_0.2_0.2:segmComp     segmComp<0.2?0.2:segmComp     segmComp                                                        'D'    [0.20000000298,1]
fv_nC>25?25:fv_nC             fv_nC_25_25:fv_nC             fv_nC>25?25:fv_nC             fv_nC                                                           'D'    [7.6161340985e-05,25]
fv_dphi3D>0.15?0.15:fv_dphi3D fv_dphi3D_0.15_0.15:fv_dphi3D fv_dphi3D>0.15?0.15:fv_dphi3D fv_dphi3D                                                       'D'    [0,0.15000000596]
fv_d3Dsig>100?100:fv_d3Dsig   fv_d3Dsig_100_100:fv_d3Dsig   fv_d3Dsig>100?100:fv_d3Dsig   fv_d3Dsig                                                       'D'    [0.452563643456,100]
mindca_iso>0.5?0.5:mindca_iso mindca_iso_0.5_0.5:mindca_iso mindca_iso>0.5?0.5:mindca_iso mindca_iso                                                      'D'    [2.11501264857e-05,0.5]
trkRel>10?10:trkRel           trkRel_10_10:trkRel           trkRel>10?10:trkRel           trkRel                                                          'D'    [0,10]
MuonIDeval_Mu1.MuonID         MuonIDeval_Mu1.MuonID         MuonIDeval_Mu1.MuonID         MuonIDeval_Mu1.MuonID                                           'D'    [0.0874381586909,0.721137523651]
MuonIDeval_Mu2.MuonID         MuonIDeval_Mu2.MuonID         MuonIDeval_Mu2.MuonID         MuonIDeval_Mu2.MuonID                                           'D'    [0.0800769850612,0.708489596844]
MuonIDeval_Mu3.MuonID         MuonIDeval_Mu3.MuonID         MuonIDeval_Mu3.MuonID         MuonIDeval_Mu3.MuonID                                           'D'    [0.0821049660444,0.70669478178]
MuonIDeval_Mu3.year           MuonIDeval_Mu3.year           MuonIDeval_Mu3.year           MuonIDeval_Mu3.year                                             'D'    [2017,2018]
std::fmin(std::fmin(abs(dxy1)/dxyErr1,abs(dxy2)/dxyErr2),abs(dxy3)/dxyErr3)     std_fmin_std_fmin_abs_dxy1__D_dxyErr1,abs_dxy2__D_dxyErr2_,abs_dxy3__D_dxyErr3_ std::fmin(std::fmin(abs(dxy1)/dxyErr1,abs(dxy2)/dxyErr2),abs(dxy3)/dxyErr3)     d0sig_min                                                                                                                                                           'D'    [2.3814038741e-06,82.966506958]
std::fmax(std::fmax(abs(dxy1)/dxyErr1,abs(dxy2)/dxyErr2),abs(dxy3)/dxyErr3)     std_fmax_std_fmax_abs_dxy1__D_dxyErr1,abs_dxy2__D_dxyErr2_,abs_dxy3__D_dxyErr3_ std::fmax(std::fmax(abs(dxy1)/dxyErr1,abs(dxy2)/dxyErr2),abs(dxy3)/dxyErr3)     d0sig_max                                                                                                                                                           'D'    [0.0533082857728,275.145080566]
NSpec 4
tripletMass                   tripletMass                   tripletMass                   tripletMass                                                     'F'    [1.62000739574,1.99999523163]
tripletMassReso               tripletMassReso               tripletMassReso               tripletMassReso                                                 'F'    [0.00348273618147,0.00699990103021]
puFactor                      puFactor                      puFactor                      puFactor                                                        'F'    [0,6.79774999619]
int(evt)%4096                 evt                           evt                           I                                                               'F'    [0,4095]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 15 )
   {
      // the training input variables
      const char* inputVars[] = { "Pt_tripl", "cLP>30?30:cLP", "tKink>80?80:tKink", "segmComp<0.2?0.2:segmComp", "fv_nC>25?25:fv_nC", "fv_dphi3D>0.15?0.15:fv_dphi3D", "fv_d3Dsig>100?100:fv_d3Dsig", "mindca_iso>0.5?0.5:mindca_iso", "trkRel>10?10:trkRel", "MuonIDeval_Mu1.MuonID", "MuonIDeval_Mu2.MuonID", "MuonIDeval_Mu3.MuonID", "MuonIDeval_Mu3.year", "std::fmin(std::fmin(abs(dxy1)/dxyErr1,abs(dxy2)/dxyErr2),abs(dxy3)/dxyErr3)", "std::fmax(std::fmax(abs(dxy1)/dxyErr1,abs(dxy2)/dxyErr2),abs(dxy3)/dxyErr3)" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
